spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    ##add-mappings: false
    static-locations: classpath:/static/
  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    suffix: .html

ribbon:
  ReadTimeout: 60000
  SocketTimeout: 30000
  ConnectTimeout: 30000
feign:
  httpclient:
    connection-timeout: 60000
uuid:
  workerId: 9
  datacenterId: 9
mybatis-plus:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: meng.klj.upms.*.entity
  global-config:
    db-config:
      id-type: id_worker
server:
  port: 8666
